ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py 2021-11-16 16:05:05,036
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: posts1.html, myapp/post_list.html
ERROR "GET /news/ HTTP/1.1" 500 84985 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py 2021-11-16 16:05:05,057
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py 2021-11-16 16:09:19,788
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: posts1.html, myapp/post_list.html
ERROR "GET /news/ HTTP/1.1" 500 84982 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py 2021-11-16 16:09:19,813
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py 2021-11-16 16:15:50,910
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: posts.html1, myapp/post_list.html
ERROR "GET /news/ HTTP/1.1" 500 84984 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py 2021-11-16 16:15:50,916
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py 2021-11-16 16:17:16,095
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: posts.html1, myapp/post_list.html
ERROR "GET /news/ HTTP/1.1" 500 84984 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py 2021-11-16 16:17:16,099
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py 2021-11-16 16:19:23,029
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: posts.html1, myapp/post_list.html
ERROR "GET /news/ HTTP/1.1" 500 84985 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py 2021-11-16 16:19:23,062
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py 2021-11-16 16:20:38,529
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: posts.html1, myapp/post_list.html
ERROR "GET /news/ HTTP/1.1" 500 84984 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py 2021-11-16 16:20:38,534
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py 2021-11-16 16:22:13,649
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: posts1.html, myapp/post_list.html
ERROR "GET /news/ HTTP/1.1" 500 84984 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py 2021-11-16 16:22:13,655
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py 2021-11-16 16:23:43,414
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: posts3.html, myapp/post_list.html
ERROR "GET /news/ HTTP/1.1" 500 84984 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py 2021-11-16 16:23:43,420
ERROR Internal Server Error: /news/test/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-18 10:45:54,150
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR "GET /news/test/ HTTP/1.1" 500 65232 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-18 10:45:54,153
ERROR Internal Server Error: /news/test/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-18 10:47:21,809
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR "GET /news/test/ HTTP/1.1" 500 65232 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-18 10:47:21,812
ERROR Internal Server Error: /news/test/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-18 10:50:16,415
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR "GET /news/test/ HTTP/1.1" 500 65369 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-18 10:50:16,457
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-22 14:06:13,648
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'get_languages_info_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Program Files\python\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\python\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 63: 'get_languages_info_list'. Did you forget to register or load this tag?
ERROR "GET /news/ HTTP/1.1" 500 177362 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-22 14:06:13,719
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-22 15:29:23,443
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Program Files\python\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\python\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 60: 'get_current_languages'. Did you forget to register or load this tag?
ERROR "GET /news/ HTTP/1.1" 500 172387 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-22 15:29:23,973
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-22 15:30:10,376
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Program Files\python\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\python\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 60: 'get_current_languages'. Did you forget to register or load this tag?
ERROR "GET /news/ HTTP/1.1" 500 172387 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-22 15:30:10,543
ERROR Internal Server Error: / C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-22 16:04:29,544
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'get_current_languages'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "C:\Program Files\python\lib\site-packages\django\contrib\flatpages\middleware.py", line 12, in process_response
    return flatpage(request, request.path_info)
  File "C:\Program Files\python\lib\site-packages\django\contrib\flatpages\views.py", line 45, in flatpage
    return render_flatpage(request, f)
  File "C:\Program Files\python\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\django\contrib\flatpages\views.py", line 59, in render_flatpage
    template = loader.select_template((f.template_name, DEFAULT_TEMPLATE))
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\python\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 60: 'get_current_languages'. Did you forget to register or load this tag?
ERROR "GET / HTTP/1.1" 500 143749 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-22 16:04:29,573
ERROR Internal Server Error: / C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-22 16:04:59,181
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'get_available_language'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\utils\deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "C:\Program Files\python\lib\site-packages\django\contrib\flatpages\middleware.py", line 12, in process_response
    return flatpage(request, request.path_info)
  File "C:\Program Files\python\lib\site-packages\django\contrib\flatpages\views.py", line 45, in flatpage
    return render_flatpage(request, f)
  File "C:\Program Files\python\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\django\contrib\flatpages\views.py", line 59, in render_flatpage
    template = loader.select_template((f.template_name, DEFAULT_TEMPLATE))
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\python\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 63: 'get_available_language'. Did you forget to register or load this tag?
ERROR "GET / HTTP/1.1" 500 145461 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-22 16:04:59,187
ERROR Internal Server Error: /news/test/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-23 16:02:20,306
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR "GET /news/test/ HTTP/1.1" 500 70552 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-23 16:02:20,337
ERROR Internal Server Error: /news/test/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-23 16:02:31,232
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
TypeError: get() takes 1 positional argument but 2 were given
ERROR "GET /news/test/ HTTP/1.1" 500 70682 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-23 16:02:31,243
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-24 14:19:07,766
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: 'tz=='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Program Files\python\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\python\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\python\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\python\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Program Files\python\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Program Files\python\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Program Files\python\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '==' from 'tz=='
ERROR "GET /news/ HTTP/1.1" 500 207051 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-24 14:19:07,901
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-24 14:25:18,089
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Program Files\python\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\devD\NP_news\NP_news\myapp\views.py", line 48, in post
    request.sessions['django_timezone']= request.POST['timezone']
AttributeError: 'WSGIRequest' object has no attribute 'sessions'
ERROR "POST /news/ HTTP/1.1" 500 80667 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-24 14:25:18,173
ERROR Internal Server Error: /news/ C:\Program Files\python\lib\site-packages\django\utils\log.py (exc_info) 2021-11-24 15:00:49,038
Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\template\smartif.py", line 175, in translate_token
    op = OPERATORS[token]
KeyError: '>=19'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Program Files\python\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Program Files\python\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Program Files\python\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Program Files\python\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Program Files\python\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Program Files\python\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Program Files\python\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "C:\Program Files\python\lib\site-packages\django\template\defaulttags.py", line 897, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Program Files\python\lib\site-packages\django\template\smartif.py", line 166, in __init__
    mapped_tokens.append(self.translate_token(token))
  File "C:\Program Files\python\lib\site-packages\django\template\smartif.py", line 177, in translate_token
    return self.create_var(token)
  File "C:\Program Files\python\lib\site-packages\django\template\defaulttags.py", line 900, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Program Files\python\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '>=19' from '>=19'
ERROR "GET /news/ HTTP/1.1" 500 238804 C:\Program Files\python\lib\site-packages\django\core\servers\basehttp.py (exc_info) 2021-11-24 15:00:49,180
